project_id = "gemhywggtdryovqmalqh"

[functions.send-meeting-notifications]
verify_jwt = false

[functions.cleanup-ics-files]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.create-custom-audit-page]
verify_jwt = false